### PR TITLE
Correction in case of spaces in filenames

### PR DESCRIPTION
**Pull request by jchome**
Change the way that arguments are passed to scripts

### CODE REVIEW

**Comment by Nexucis** [comment]
I don't really see why this PR fixes the case of space in filename. From my point of view, you just change the way that find print the result : 

### with the current version

```bash
find ./ -type f -name "$var" -print0
```
which print alll result in a single line

### with this PR

```bash
find ./ -type f -name "$var" -print
```
which print one result per line.


And finally the test failed.

**Comment by jchome** [comment]
If you do this following command line:
`find ./ -type f -name "$var" -print0 | xargs -0 eol_if`

The "-print0" parameter does a cut on filenames of the list of files found by the `find` program (as expected). But it also cuts any filename that has a at least one space character. So, when you do the test on "my file.txt", it runs the script `eol_if` twice:
 
1. `eol_if my`
2. `eol_if file.txt`

These files do not exist and the test fails.

**Comment by Nexucis** [comment]
Thanks for the explanation :) it's more clear now.

Can you fix the test please ? You can see that the build doesn't pass :/.

**Comment by jchome** [comment]
I found a little of time to correct the script I've updated.

**Pull request merged**
